### PR TITLE
Update Method Name To Avoid the React Warning

### PR DESCRIPTION
**Pull request by xiCO2k**

### CODE REVIEW

**Comment by kopax** [comment]
Hello, any plan to merge this? @xiCO2k is your version available on npm?

**Comment by xiCO2k** [comment]
Hey @kopax not available on NPM

**Comment by xiCO2k** [comment]
Still waiting to my pull request to be merged

**Review by mafortier-nexapp — APPROVED** [review]

**Comment by kopax** [comment]
I have created my own repo with the 3 PR not merged and releases. It would be nice to have someone that takes care of it and produce the new version with it.

**Comment by LcsLpr** [comment]
@kopax  do you have the enhanced  version ?  "modal-enhanced-react-native-web": "^0.2.0" has the same issue

**Pull request closed without merging**
